language: generic
addons:
  apt:
    packages:
      - xmlstarlet
      - xsltproc
before_install:
    - rvm install 2.3.8
script:
    - xmlstarlet val -e Sources/*.xml
    - xmlstarlet val -e Collections/*.xml
    - xmlstarlet val -e -s Utilities/collection.xsd Collections/*.xml
    - xmlstarlet val -e -s Utilities/compendium.xsd FightClub5eXML/Sources/*.xml
    - for i in Collections/*.xml; do xsltproc --xinclude -o Compendiums/$i Utilities/merge.xslt $i; done
