name: Compile all collections into compendiums
on: 
  push:
    branches: [ master ]
    tags:
      - '*'
  workflow_dispatch:
  pull_request:

jobs:
  compile_collections:
    name: Compile collections
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install xsltproc and parallel
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: xsltproc
          version: 1.0

      - name: Compile collections into compendiums
        run: |
          set -euxo pipefail
          trap 'echo "Error occurred during compilation!"' ERR

          mkdir -p Compendiums
          for f in Collections/*.xml; do
            filename=$(basename "$f")
            echo "Compiling $filename ..."
            xsltproc --xinclude -o "Compendiums/$filename" "Utilities/merge.xslt" "$f"
          done

      - name: Upload compiled XML files as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: compendiums-${{ github.ref_name }}
          path: Compendiums/

      # Create a GitHub release when a tag is pushed
      - name: Create versioned release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Compendiums/*

      # Update the nightly release only on master branch push
      - name: Update nightly release
        if: github.ref == 'refs/heads/master'
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: Compendiums/*
